version: "3"
services:
  travel_itinerary:
    container_name: travel_itinerary
    environment:
      - BUNDLE_PATH=/gems
      - BUNDLE_FROZEN=false
    build: .
    command: >
      bundle install && bundle exec rails s -p 3002 -b '0.0.0.0'
    ports:
      - "3002:3002"
    volumes:
      - bundle_data:/bundle
      - ./gems:/gems
      - ".:/rails"
  postgres:
    container_name: travel_itinerary_postgres
    hostname: postgres
    image: arm64v8/postgres:14-alpine
    shm_size: 2gb
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data/pgdata
      - ./gems:/gems
    environment:
      - POSTGRES_PASSWORD=senha
      - POSTGRES_INITDB_ARGS="--auth-host=md5"
      - PGDATA=/var/lib/postgresql/data/pgdata
volumes:
  bundle_data: {}
