# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  encoding: unicode
  host: postgres
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: travel_itinerary_development
  username: pguser
  password: pgpwd

test:
  <<: *default
  database: travel_itinerary_test
  username: pguser
  password: pgpwd

production:
  <<: *default
  database: travel_itinerary_production
  username: travel_itinerary
  username: pguser
  password: pgpwd